load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "xbar_lib",
    srcs = ["main.go"],
    importpath = "xbar/cmd/xbar",
    visibility = ["//visibility:private"],
    deps = ["//plugins/prs"],
)

go_binary(
    name = "xbar",
    embed = [":xbar_lib"],
    visibility = ["//visibility:public"],
)
